
export const SJSU_SUBJECTS = [
  'AAS', 'ADV', 'AE', 'AFAM', 'AFRS', 'AMS', 'ANI', 'ANTH', 'APSC', 'ARED', 
  'ART', 'ARTH', 'AS', 'ASIA', 'ASTR', 'ATH', 'AUD', 'AVIA', 'BIOL', 'BME', 
  'BOT', 'BUS', 'BUS1', 'BUS2', 'BUS3', 'BUS4', 'BUS5', 'CA', 'CCS', 'CE', 
  'CHAD', 'CHE', 'CHEM', 'CHHS', 'CHIN', 'CMPE', 'COLT', 'COMM', 'CS', 'DANC', 
  'DATA', 'DSGD', 'DSGN', 'DSID', 'DSIT', 'ECON', 'EDAD', 'EDAU', 'EDCO', 'EDD', 
  'EDEL', 'EDLD', 'EDSC', 'EDSE', 'EDSP', 'EDTE', 'EDUC', 'EE', 'ENED', 'ENGL', 
  'ENGR', 'ENT', 'ENVS', 'FLED', 'FORL', 'FREN', 'FS', 'GEOG', 'GEOL', 'GERM', 
  'GERO', 'GLST', 'HA', 'HEBR', 'HIST', 'HPRF', 'HS', 'HSPM', 'HUM', 'INFM', 
  'INFO', 'ISDA', 'ISE', 'ITAL', 'JOUR', 'JPN', 'JS', 'JWSS', 'KIN', 'KNED', 
  'LING', 'LLD', 'LSTP', 'MARA', 'MAS', 'MATE', 'MATH', 'MCOM', 'MDES', 'ME', 
  'METR', 'MICR', 'MILS', 'MS', 'MTED', 'MTM', 'MUED', 'MUSC', 'NUCS', 'NUFS', 
  'NURS', 'OCTH', 'ORGS', 'PADM', 'PH', 'PHIL', 'PHOT', 'PHYS', 'PKG', 'POLS', 
  'PORT', 'PR', 'PSYC', 'RECL', 'RELS', 'RTVF', 'RUSS', 'SCED', 'SCI', 'SCWK', 
  'SE', 'SMPD', 'SOCI', 'SOCS', 'SPAN', 'SPED', 'SSCI', 'SSED', 'STAT', 'TA', 
  'TAG', 'TECH', 'UNVS', 'URBP', 'VIET', 'WGSS', 'WOMS', 'XGADM', 'XMPRJM', 
  'XOC', 'XRS', 'XWC', 'ZOOL'
].sort();

export const SJSU_DEPARTMENTS = [
  'African American Studies',
  'Aerospace Engineering',
  'Anthropology',
  'Art and Art History',
  'Aviation and Technology',
  'Biological Sciences',
  'Biomedical Engineering',
  'Chemical and Materials Engineering',
  'Chemistry',
  'Chicana and Chicano Studies',
  'Child and Adolescent Development',
  'Civil and Environmental Engineering',
  'Communication Studies',
  'Computer Engineering',
  'Computer Science',
  'Counselor Education',
  'Design (Graphic, Interior, Industrial, Animation/Illustration)',
  'Economics',
  'Educational Leadership',
  'Electrical Engineering',
  'Elementary Education',
  'Engineering (General)',
  'English and Comparative Literature',
  'Environmental Studies',
  'Film and Theatre',
  'Geography',
  'Geology',
  'Health Science and Recreation',
  'History',
  'Hospitality, Tourism and Event Management',
  'Humanities',
  'Industrial and Systems Engineering',
  'Information Systems and Technology',
  'Instructional Technology',
  'Interdisciplinary Studies',
  'Journalism and Mass Communications',
  'Justice Studies',
  'Kinesiology',
  'Linguistics and Language Development',
  'Marketing and Business Analytics',
  'Mathematics and Statistics',
  'Mechanical Engineering',
  'Meteorology and Climate Science',
  'Music',
  'Nursing',
  'Nutrition, Food Science, and Packaging',
  'Occupational Therapy',
  'Philosophy',
  'Physics and Astronomy',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Recreation',
  'Religious Studies',
  'Science Education',
  'Social Work',
  'Sociology and Interdisciplinary Social Sciences',
  'Special Education',
  'Teacher Education (Multiple Subjects / Single Subject)',
  'Theatre and Dance',
  'Urban and Regional Planning',
  'Women, Gender & Sexuality Studies',
  'World Languages and Literatures'
];
